using Microsoft.Win32;
namespace MeshDriveSync;
public sealed class MainForm:Form{
 readonly AppSettings settings=AppSettings.Load();readonly DataGridView grid=new(){Dock=DockStyle.Fill,AutoGenerateColumns=false,AllowUserToAddRows=false,SelectionMode=DataGridViewSelectionMode.FullRowSelect,MultiSelect=false,ReadOnly=true};readonly NotifyIcon tray=new(){Visible=true,Text="Mesh Drive Sync"};readonly Dictionary<string,SyncEngine> engines=new();readonly System.Windows.Forms.Timer timer=new();
 public MainForm(bool background){Text="Mesh Drive Sync v3.0.8";Width=1080;Height=620;StartPosition=FormStartPosition.CenterScreen;ApplyIcon();Build();BuildTray();RefreshGrid();timer.Interval=Math.Max(15,settings.MappingCheckSeconds)*1000;timer.Tick+=async(_,_)=>await MaintainMappings();timer.Start();Shown+=async(_,_)=>{if(background||settings.StartMinimized)Hide();await MaintainMappings();};FormClosing+=(_,e)=>{if(e.CloseReason==CloseReason.UserClosing){e.Cancel=true;Hide();}};}
 void ApplyIcon(){try{var i=Icon.ExtractAssociatedIcon(Application.ExecutablePath);if(i!=null){Icon=(Icon)i.Clone();tray.Icon=(Icon)i.Clone();i.Dispose();}else tray.Icon=SystemIcons.Application;}catch{tray.Icon=SystemIcons.Application;}}
 void Build(){foreach(var c in new[]{("Nome","Name",190),("Servidor","Host",225),("Pasta remota","Folder",150),("Unidade","Drive",75),("Permissão","Access",145),("Estado","Status",140),("Sync","Sync",65)})grid.Columns.Add(new DataGridViewTextBoxColumn{HeaderText=c.Item1,DataPropertyName=c.Item2,Width=c.Item3});Controls.Add(grid);var bar=new FlowLayoutPanel{Dock=DockStyle.Top,Height=48,Padding=new Padding(8)};Controls.Add(bar);Btn(bar,"Adicionar",Add);Btn(bar,"Editar",Edit);Btn(bar,"Remover",Remove);Btn(bar,"Conectar",async()=>await ConnectSelected());Btn(bar,"Desconectar",DisconnectSelected);Btn(bar,"Verificar permissão",async()=>await DetectSelected());Btn(bar,"Abrir unidade",OpenSelected);}
 static void Btn(Control p,string text,Action action){var b=new Button{Text=text,AutoSize=true,Height=32};b.Click+=(_,_)=>action();p.Controls.Add(b);}void BuildTray(){var m=new ContextMenuStrip();m.Items.Add("Abrir Mesh Drive Sync",null,(_,_)=>ShowApp());m.Items.Add("Reconectar todos",null,async(_,_)=>await MaintainMappings(true));m.Items.Add(new ToolStripSeparator());m.Items.Add("Sair",null,(_,_)=>{tray.Visible=false;Application.Exit();});tray.ContextMenuStrip=m;tray.DoubleClick+=(_,_)=>ShowApp();}
 void ShowApp(){Show();WindowState=FormWindowState.Normal;Activate();}MappingProfile? Selected()=>grid.SelectedRows.Count==0?null:settings.Mappings.FirstOrDefault(x=>x.Id==(string)grid.SelectedRows[0].Cells[0].Tag!);void RefreshGrid(){grid.Rows.Clear();foreach(var p in settings.Mappings){var connected=NetworkDriveManager.IsConnected(p);var i=grid.Rows.Add(p.Name,p.Host,string.IsNullOrEmpty(p.RemoteFolder)?"Raiz":p.RemoteFolder,(string.IsNullOrEmpty(p.ActiveDriveLetter)?p.PreferredDriveLetter:p.ActiveDriveLetter)+":",AccessText(p.Access),connected?"Conectado":"Desconectado",p.SyncEnabled?"Ativo":"Não");grid.Rows[i].Cells[0].Tag=p.Id;}}
 static string AccessText(AccessMode a)=>a switch{AccessMode.ReadOnly=>"Somente leitura",AccessMode.ReadWrite=>"Leitura e gravação",AccessMode.NoAccess=>"Sem acesso",_=>"Não verificada"};
 void Add(){var p=new MappingProfile();using var d=new ProfileDialog(p);if(d.ShowDialog()==DialogResult.OK){settings.Mappings.Add(p);Save();}}void Edit(){var p=Selected();if(p==null)return;using var d=new ProfileDialog(p);if(d.ShowDialog()==DialogResult.OK)Save();}void Remove(){var p=Selected();if(p==null)return;Disconnect(p);settings.Mappings.Remove(p);Save();}
 async Task ConnectSelected(){var p=Selected();if(p!=null){await Connect(p);Save();}}void DisconnectSelected(){var p=Selected();if(p!=null){Disconnect(p);Save();}}void OpenSelected(){var p=Selected();if(p==null||string.IsNullOrEmpty(p.ActiveDriveLetter))return;System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(p.ActiveDriveLetter+":\\"){UseShellExecute=true});}
 async Task DetectSelected(){var p=Selected();if(p==null)return;var c=CredentialManager.Read(p.CredentialTarget);if(c==null){MessageBox.Show("Edite o perfil e salve usuário e senha primeiro.");return;}using var dav=new WebDavClient(p,c.Value.Password);p.Access=await dav.DetectAccess(CancellationToken.None);if(p.Access!=AccessMode.ReadWrite){p.SyncEnabled=false;StopSync(p);}Save();MessageBox.Show("Permissão detectada: "+AccessText(p.Access),"Mesh Drive Sync");}
 async Task Connect(MappingProfile p){try{var c=CredentialManager.Read(p.CredentialTarget);if(c==null)return;p.Username=c.Value.User;if(!NetworkDriveManager.IsConnected(p))NetworkDriveManager.Connect(p,c.Value.Password);using var dav=new WebDavClient(p,c.Value.Password);p.Access=await dav.DetectAccess(CancellationToken.None);if(p.Access==AccessMode.ReadWrite&&p.SyncEnabled)StartSync(p,c.Value.Password);else{p.SyncEnabled=false;StopSync(p);}}catch(Exception ex){Log(p,ex.Message);}}
 void Disconnect(MappingProfile p){StopSync(p);NetworkDriveManager.Disconnect(p);}void StartSync(MappingProfile p,string pass){if(engines.ContainsKey(p.Id))return;p.LocalFolder=p.EffectiveLocalFolder;var e=new SyncEngine(p,pass,x=>Log(p,x.Status+(string.IsNullOrEmpty(x.File)?"":" - "+x.File)));engines[p.Id]=e;e.Start();}void StopSync(MappingProfile p){if(engines.Remove(p.Id,out var e))e.Dispose();}
 async Task MaintainMappings(bool force=false){foreach(var p in settings.Mappings.Where(x=>x.Enabled&&x.ConnectAtLogon)){if(force||!NetworkDriveManager.IsConnected(p))await Connect(p);}Save();}
 void Save(){settings.StartWithWindows=settings.Mappings.Any(x=>x.Enabled&&x.ConnectAtLogon);settings.Save();SetStartup();RefreshGrid();}
 void SetStartup(){using var k=Registry.CurrentUser.CreateSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run");var shouldStart=settings.Mappings.Any(x=>x.Enabled&&x.ConnectAtLogon);if(shouldStart)k.SetValue("MeshDriveSync","\""+Application.ExecutablePath+"\" --background");else k.DeleteValue("MeshDriveSync",false);foreach(var name in k.GetValueNames().Where(x=>x.StartsWith("MeshDriveSync-",StringComparison.OrdinalIgnoreCase)).ToList())k.DeleteValue(name,false);}static void Log(MappingProfile p,string text){Directory.CreateDirectory(p.DataFolder);File.AppendAllText(p.LogFile,DateTime.Now+" "+text+Environment.NewLine);}protected override void Dispose(bool disposing){if(disposing){timer.Dispose();foreach(var e in engines.Values)e.Dispose();tray.Dispose();}base.Dispose(disposing);}
}
