namespace MeshDriveSync;
public sealed class ProfileDialog:Form{
 readonly TextBox name=new(),host=new(),user=new(),password=new(){UseSystemPasswordChar=true},local=new();
 readonly ComboBox folder=new(){DropDownStyle=ComboBoxStyle.DropDownList},letter=new(){DropDownStyle=ComboBoxStyle.DropDownList};
 readonly CheckBox autoReconnect=Option("Restabelecer automaticamente o mapeamento se a conexão cair"),connectLogon=Option("Iniciar este mapeamento automaticamente com o Windows"),sync=Option("Manter uma cópia sincronizada desta pasta no computador");
 readonly Label access=new(){AutoSize=true,Text="Permissão ainda não verificada."},syncHelp=new(){AutoSize=true,ForeColor=Color.DimGray,Text="A sincronização só será liberada quando o servidor confirmar permissão de gravação."};
 public MappingProfile Profile{get;}
 public ProfileDialog(MappingProfile p){Profile=p;Text="Configurar mapeamento";Width=760;Height=570;StartPosition=FormStartPosition.CenterParent;AutoScroll=true;ApplyIcon();var grid=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(20),ColumnCount=3,AutoScroll=true};grid.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,190));grid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));grid.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,145));Controls.Add(grid);Add(grid,"Nome do mapeamento",name);Add(grid,"Domínio Mesh",host);Add(grid,"Usuário",user);Add(grid,"Senha",password);Add(grid,"Pasta do Mesh Drive",folder,"Listar pastas",async()=>await ListFolders());Add(grid,"Letra da unidade",letter);Add(grid,"Pasta local",local,"Selecionar",ChooseLocal);AddWide(grid,access);AddWide(grid,connectLogon);AddWide(grid,autoReconnect);AddWide(grid,sync);AddWide(grid,syncHelp);var save=new Button{Text="Salvar",AutoSize=true,Height=36};save.Click+=(_,_)=>Save();grid.Controls.Add(save,1,grid.RowCount++);name.Text=p.Name;host.Text=p.Host;user.Text=p.Username;local.Text=p.EffectiveLocalFolder;LoadLetters(p.PreferredDriveLetter);folder.Items.Add("(Raiz do Mesh Drive)");folder.SelectedIndex=0;if(!string.IsNullOrWhiteSpace(p.RemoteFolder)){folder.Items.Add(p.RemoteFolder);folder.SelectedItem=p.RemoteFolder;}autoReconnect.Checked=p.AutoReconnect;connectLogon.Checked=p.ConnectAtLogon;UpdatePermissionUi();name.TextChanged+=(_,_)=>RefreshLocalPreview();host.TextChanged+=(_,_)=>RefreshLocalPreview();}
 void ApplyIcon(){try{var i=Icon.ExtractAssociatedIcon(Application.ExecutablePath);if(i!=null){Icon=(Icon)i.Clone();i.Dispose();}else Icon=SystemIcons.Application;}catch{Icon=SystemIcons.Application;}}
 void RefreshLocalPreview(){var baseFolder=string.IsNullOrWhiteSpace(Profile.LocalBaseFolder)?Environment.GetFolderPath(Environment.SpecialFolder.UserProfile):Profile.LocalBaseFolder;local.Text=MappingProfile.BuildLocalFolder(baseFolder,host.Text,name.Text);}
 void LoadLetters(string preferred){letter.Items.Clear();foreach(var l in NetworkDriveManager.AvailableLetters())letter.Items.Add(l+":");var wanted=preferred.Trim().TrimEnd(':')+":";if(letter.Items.Contains(wanted))letter.SelectedItem=wanted;else if(letter.Items.Count>0)letter.SelectedIndex=0;}
 static CheckBox Option(string text)=>new(){Text=text,AutoSize=true,MaximumSize=new Size(500,0),Anchor=AnchorStyles.Left};
 static void Add(TableLayoutPanel g,string label,Control c,string? button=null,Action? action=null){var r=g.RowCount++;g.RowStyles.Add(new RowStyle(SizeType.AutoSize));g.Controls.Add(new Label{Text=label,AutoSize=true,Anchor=AnchorStyles.Left},0,r);c.Dock=DockStyle.Top;c.Margin=new Padding(3,5,8,8);g.Controls.Add(c,1,r);if(button!=null){var b=new Button{Text=button,Dock=DockStyle.Top,Height=30};b.Click+=(_,_)=>action?.Invoke();g.Controls.Add(b,2,r);}}
 static void AddWide(TableLayoutPanel g,Control c){var r=g.RowCount++;g.RowStyles.Add(new RowStyle(SizeType.AutoSize));g.Controls.Add(c,1,r);g.SetColumnSpan(c,2);c.Anchor=AnchorStyles.Left|AnchorStyles.Right;c.AutoSize=true;c.Margin=new Padding(3,5,3,7);}
 async Task ListFolders(){try{SaveCredentialOnly();var c=CredentialManager.Read(Profile.CredentialTarget);if(c==null)throw new Exception("Informe usuário e senha.");var rootProfile=new MappingProfile{Host=host.Text.Trim(),Username=user.Text.Trim(),RemoteFolder=""};using var dav=new WebDavClient(rootProfile,c.Value.Password);var items=await dav.RootFolders(CancellationToken.None);folder.Items.Clear();folder.Items.Add("(Raiz do Mesh Drive)");foreach(var f in items)folder.Items.Add(f);folder.SelectedIndex=0;MessageBox.Show($"{items.Count} pasta(s) encontrada(s).","Mesh Drive Sync");}catch(Exception ex){MessageBox.Show(ex.Message,"Falha ao listar",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
 void ChooseLocal(){using var d=new FolderBrowserDialog{Description=@"Selecione a pasta onde será criada a estrutura Mesh Drive\Domínio\Perfil"};if(d.ShowDialog()==DialogResult.OK){Profile.LocalBaseFolder=d.SelectedPath;RefreshLocalPreview();}}
 void SaveCredentialOnly(){Profile.Host=host.Text.Trim();Profile.Username=user.Text.Trim();if(password.TextLength>0)CredentialManager.Save(Profile.CredentialTarget,Profile.Username,password.Text);}
 void UpdatePermissionUi(){access.Text=Profile.Access switch{AccessMode.ReadOnly=>"Permissão: somente leitura. O mapeamento será permitido, mas a sincronização ficará indisponível.",AccessMode.ReadWrite=>"Permissão: leitura e gravação. Mapeamento e sincronização disponíveis.",AccessMode.NoAccess=>"Permissão: sem acesso.",_=>"Permissão ainda não verificada. Será verificada ao conectar."};sync.Visible=Profile.Access!=AccessMode.ReadOnly&&Profile.Access!=AccessMode.NoAccess;syncHelp.Visible=Profile.Access!=AccessMode.ReadWrite;sync.Checked=Profile.SyncEnabled&&Profile.Access==AccessMode.ReadWrite;}
 void Save(){Profile.Name=name.Text.Trim();Profile.Host=host.Text.Trim();Profile.Username=user.Text.Trim();Profile.RemoteFolder=folder.SelectedIndex<=0?"":folder.SelectedItem?.ToString()??"";Profile.PreferredDriveLetter=(letter.SelectedItem?.ToString()??"M:").TrimEnd(':');Profile.LocalFolder=MappingProfile.BuildLocalFolder(string.IsNullOrWhiteSpace(Profile.LocalBaseFolder)?Environment.GetFolderPath(Environment.SpecialFolder.UserProfile):Profile.LocalBaseFolder,Profile.Host,Profile.Name);Profile.AutoSelectDriveLetter=false;Profile.AutoReconnect=autoReconnect.Checked;Profile.ConnectAtLogon=connectLogon.Checked;Profile.SyncEnabled=Profile.Access==AccessMode.ReadWrite&&sync.Checked;if(password.TextLength>0)CredentialManager.Save(Profile.CredentialTarget,Profile.Username,password.Text);DialogResult=DialogResult.OK;Close();}
}
